[platformio]
default_envs = display1

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
  mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@^3.0.10
  knolleary/PubSubClient@^2.8
  arduino-libraries/Ethernet@^2.0.2
  bblanchon/ArduinoJson@^7.0.4
build_flags =
  -DCORE_DEBUG_LEVEL=1

[env:display1]
extends = env
build_flags = ${env.build_flags} -DDISPLAY_ID=1
[env:display2]
extends = env
build_flags = ${env.build_flags} -DDISPLAY_ID=2
[env:display3]
extends = env
build_flags = ${env.build_flags} -DDISPLAY_ID=3
[env:display4]
extends = env
build_flags = ${env.build_flags} -DDISPLAY_ID=4
[env:display5]
extends = env
build_flags = ${env.build_flags} -DDISPLAY_ID=5
[env:display6]
extends = env
build_flags = ${env.build_flags} -DDISPLAY_ID=6
[env:display7]
extends = env
build_flags = ${env.build_flags} -DDISPLAY_ID=7
